baseurl = "http://www.example.com"
title = "Pavel Gordon"
theme = "hugo-coder"
languagecode = "en"
defaultcontentlanguage = "en"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "Pavel Gordon"
    info = "Backend(Java/Kotlin) Engineer"
    description = "Pavel Gordon's personal website"
    keywords = "blog,developer,personal,engineer"
    avatarurl = "images/avatar.jpg"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    footercontent = ""

    hidecredits = false
    hidecopyright = false

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/pavelgordon/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter fa-2x"
    weight = 3
    url = "https://twitter.com/pavelgordon/"
[[params.social]]
    name = "Instagram"
    icon = "fab fa-instagram fa-2x"
    weight = 2
    url = "https://instagram.com/gordon.pawel/"
[[params.social]]
    name = "Telegram"
    icon = "fab fa-telegram fa-2x"
    weight = 2
    url = "https://t.me/freemahn"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"